# Generated by Django 2.2.16 on 2021-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_badgeclass_badgr_server_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='badgr_server_slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
